"""Platform-neutral SkillAdam product protocols and workflows."""

from skilladam.product.models import (
    EvaluationKind,
    EvaluationPlan,
    EvaluationSpec,
    GateResult,
    OptimizationSession,
    OptimizationTask,
    SessionState,
    SkillPackageSnapshot,
    TaskDraft,
    TaskPool,
    TaskSource,
    TaskSplit,
    TaskSuite,
    UsageIntent,
    ValidationResult,
    canonical_json,
    digest_value,
)
from skilladam.product.evaluation import (
    EvaluationError,
    EvaluationOutcome,
    EvaluationRunner,
    assert_same_evaluation_plan,
    evaluate_output,
)
from skilladam.product.evaluation_planning import (
    EvaluationPlanner,
    EvaluationPlanningError,
)
from skilladam.product.feedback import (
    IterationFeedback,
    MomentumUpdateContext,
    PatchGeneration,
    ProductTrajectory,
    build_iteration_feedback,
    extract_final_output,
)
from skilladam.product.patch_review import (
    CandidateSnapshot,
    PatchHunk,
    PatchProposal,
    PatchReviewError,
    PatchSelection,
    apply_patch_selection,
    prepare_patch_proposal,
    render_patch_hunks,
    selected_patch_diff,
    select_patch_hunks,
)
from skilladam.product.tasking import (
    SYNTHETIC_COVERAGE,
    SyntheticGenerationRequest,
    TaskIngestionError,
    derive_task_pool,
    freeze_task_pool,
    freeze_task_suite,
    generate_synthetic_tasks,
    ingest_task_records,
    ingest_user_tasks,
)
from skilladam.product.task_manifest import (
    HOST_TASK_SOURCES,
    TASK_DIFFICULTIES,
    TASK_MANIFEST_SCHEMA_VERSION,
    ingest_task_manifest,
    task_manifest_schema,
)
from skilladam.product.session_store import SessionStore
from skilladam.product.workflow import (
    OptimizationWorkflow,
    OptimizationWorkflowError,
    ProductSessionView,
)
from skilladam.product.commands import (
    continue_product,
    prepare_product,
    product_status,
    submit_product_selection,
)
from skilladam.product.model import (
    FixtureProductModel,
    OpenAICompatibleProductModel,
    ProductModel,
)
from skilladam.product.project import ProductProject, ProductProjectStore
from skilladam.product.service import ProductService, ProductSourceConflict

__all__ = [
    "CandidateSnapshot",
    "EvaluationKind",
    "EvaluationError",
    "EvaluationOutcome",
    "EvaluationPlan",
    "EvaluationPlanner",
    "EvaluationPlanningError",
    "EvaluationRunner",
    "EvaluationSpec",
    "GateResult",
    "IterationFeedback",
    "MomentumUpdateContext",
    "OptimizationSession",
    "OptimizationTask",
    "OptimizationWorkflow",
    "OptimizationWorkflowError",
    "PatchHunk",
    "PatchGeneration",
    "PatchProposal",
    "PatchReviewError",
    "PatchSelection",
    "ProductModel",
    "ProductTrajectory",
    "ProductProject",
    "ProductProjectStore",
    "ProductService",
    "ProductSessionView",
    "ProductSourceConflict",
    "SessionState",
    "SessionStore",
    "SkillPackageSnapshot",
    "TaskDraft",
    "TaskPool",
    "TaskSource",
    "TaskSplit",
    "TaskSuite",
    "TaskIngestionError",
    "SyntheticGenerationRequest",
    "SYNTHETIC_COVERAGE",
    "UsageIntent",
    "ValidationResult",
    "FixtureProductModel",
    "OpenAICompatibleProductModel",
    "apply_patch_selection",
    "assert_same_evaluation_plan",
    "canonical_json",
    "build_iteration_feedback",
    "extract_final_output",
    "continue_product",
    "digest_value",
    "derive_task_pool",
    "evaluate_output",
    "freeze_task_pool",
    "freeze_task_suite",
    "generate_synthetic_tasks",
    "ingest_task_records",
    "ingest_user_tasks",
    "HOST_TASK_SOURCES",
    "TASK_DIFFICULTIES",
    "TASK_MANIFEST_SCHEMA_VERSION",
    "ingest_task_manifest",
    "task_manifest_schema",
    "prepare_patch_proposal",
    "prepare_product",
    "product_status",
    "render_patch_hunks",
    "selected_patch_diff",
    "select_patch_hunks",
    "submit_product_selection",
]
