"""Strict ingestion of host-agent-generated task manifests."""

from __future__ import annotations

import math
import re
from collections.abc import Mapping, Sequence
from typing import Any
from urllib.parse import urlparse

from skilladam.product.evaluators import (
    REFERENCE_METHODS,
    EvaluationConfigError,
    validate_check_config,
)
from skilladam.product.evaluation_semantics import (
    open_ended_exact_text_reason,
)
from skilladam.product.models import TaskDraft, TaskSource
from skilladam.product.tasking import TaskIngestionError


TASK_MANIFEST_SCHEMA_VERSION = "1"
HOST_TASK_SOURCES: Mapping[str, TaskSource] = {
    "skill_generated": "synthetic",
    "conversation": "real_session",
    "local_history": "real_session",
    "public_benchmark": "user_provided",
    "user_provided": "user_provided",
}
TASK_DIFFICULTIES = frozenset(
    {"common", "boundary", "adversarial", "regression"}
)

_TASK_FIELDS = frozenset(
    {
        "task_id",
        "prompt",
        "capability",
        "difficulty",
        "source",
        "source_ref",
        "expected_output",
        "evaluation",
        "metadata",
    }
)
_EVALUATION_FIELDS = {
    "programmatic": frozenset(
        {
            "kind",
            "checks",
            "criteria",
            "config",
            "pass_threshold",
            "failure_feedback",
        }
    ),
    "reference": frozenset(
        {
            "kind",
            "reference",
            "method",
            "criteria",
            "config",
            "pass_threshold",
            "failure_feedback",
        }
    ),
    "rubric_judge": frozenset(
        {
            "kind",
            "rubric",
            "criteria",
            "config",
            "pass_threshold",
            "failure_feedback",
        }
    ),
    "hybrid": frozenset(
        {
            "kind",
            "components",
            "weights",
            "criteria",
            "pass_threshold",
            "failure_feedback",
        }
    ),
}
_IDENTIFIER = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_CAPABILITY = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


def ingest_task_manifest(
    manifest: Mapping[str, Any],
    *,
    expected_count: int,
) -> tuple[TaskDraft, ...]:
    """Validate a complete host manifest and convert it to the TaskDraft protocol."""

    if not isinstance(manifest, Mapping):
        raise TaskIngestionError("task_manifest must be an object")
    unknown = set(manifest) - {"schema_version", "tasks"}
    if unknown:
        raise TaskIngestionError(
            f"task_manifest has unsupported fields: {sorted(unknown)}"
        )
    version = str(manifest.get("schema_version", "")).strip()
    if version != TASK_MANIFEST_SCHEMA_VERSION:
        raise TaskIngestionError(
            "task_manifest.schema_version must be '1'"
        )
    if (
        isinstance(expected_count, bool)
        or not isinstance(expected_count, int)
        or expected_count < 3
    ):
        raise TaskIngestionError("task_count must be at least 3")
    records = manifest.get("tasks")
    if not _is_array(records):
        raise TaskIngestionError("task_manifest.tasks must be an array")
    if len(records) != expected_count:
        raise TaskIngestionError(
            f"task_manifest contains {len(records)} tasks; "
            f"expected exactly {expected_count}"
        )

    drafts = tuple(
        _task_draft(record, ordinal=index)
        for index, record in enumerate(records)
    )
    identifiers = [task.task_id for task in drafts]
    if len(set(identifiers)) != len(identifiers):
        raise TaskIngestionError("task_manifest task_id values must be unique")
    prompts = [_normalized_prompt(task.prompt) for task in drafts]
    if len(set(prompts)) != len(prompts):
        raise TaskIngestionError("task_manifest prompts must be unique")
    if len({task.capability for task in drafts}) < 2:
        raise TaskIngestionError(
            "task_manifest must cover at least two capabilities"
        )
    if all(task.difficulty == "common" for task in drafts):
        raise TaskIngestionError(
            "task_manifest must include a boundary, adversarial, or "
            "regression task"
        )
    return drafts


def task_manifest_schema() -> dict[str, Any]:
    """Return a JSON Schema ready for MCP tool exposure."""

    return {
        "type": "object",
        "description": "Frozen task and evaluation manifest researched and generated by the host agent.",
        "properties": {
            "schema_version": {"type": "string", "const": "1"},
            "tasks": {
                "type": "array",
                "minItems": 3,
                "items": {
                    "type": "object",
                    "properties": {
                        "task_id": {"type": "string"},
                        "prompt": {"type": "string"},
                        "capability": {"type": "string"},
                        "difficulty": {
                            "type": "string",
                            "enum": sorted(TASK_DIFFICULTIES),
                        },
                        "source": {
                            "type": "string",
                            "enum": sorted(HOST_TASK_SOURCES),
                        },
                        "source_ref": {"type": "string"},
                        "expected_output": {},
                        "evaluation": _evaluation_schema(),
                        "metadata": {"type": "object"},
                    },
                    "required": [
                        "task_id",
                        "prompt",
                        "capability",
                        "difficulty",
                        "source",
                        "source_ref",
                        "evaluation",
                    ],
                    "additionalProperties": False,
                },
            },
        },
        "required": ["schema_version", "tasks"],
        "additionalProperties": False,
    }


def _task_draft(record: Any, *, ordinal: int) -> TaskDraft:
    field = f"task_manifest.tasks[{ordinal}]"
    if not isinstance(record, Mapping):
        raise TaskIngestionError(f"{field} must be an object")
    unknown = set(record) - _TASK_FIELDS
    if unknown:
        raise TaskIngestionError(
            f"{field} has unsupported fields: {sorted(unknown)}"
        )

    task_id = _required_text(record, "task_id", field)
    if not _IDENTIFIER.fullmatch(task_id):
        raise TaskIngestionError(
            f"{field}.task_id must be a short stable identifier"
        )
    prompt = _required_text(record, "prompt", field)
    capability = _required_text(record, "capability", field)
    if not _CAPABILITY.fullmatch(capability):
        raise TaskIngestionError(
            f"{field}.capability must be a lowercase slug"
        )
    difficulty = _required_text(record, "difficulty", field)
    if difficulty not in TASK_DIFFICULTIES:
        raise TaskIngestionError(
            f"{field}.difficulty must be one of {sorted(TASK_DIFFICULTIES)}"
        )
    source_name = _required_text(record, "source", field)
    if source_name not in HOST_TASK_SOURCES:
        raise TaskIngestionError(
            f"{field}.source must be one of {sorted(HOST_TASK_SOURCES)}"
        )
    source_ref = _required_text(record, "source_ref", field)
    if source_name == "public_benchmark" and not _is_http_url(source_ref):
        raise TaskIngestionError(
            f"{field}.source_ref must be an http(s) URL for public_benchmark"
        )
    if source_name == "local_history" and not source_ref.startswith(
        "local-history://"
    ):
        raise TaskIngestionError(
            f"{field}.source_ref must use local-history:// for local_history"
        )
    metadata = record.get("metadata", {})
    if not isinstance(metadata, Mapping):
        raise TaskIngestionError(f"{field}.metadata must be an object")
    if source_name == "local_history":
        transform = metadata.get("history_transform")
        if not isinstance(transform, str) or not transform.strip():
            raise TaskIngestionError(
                f"{field}.metadata.history_transform must describe how the "
                "history request became a self-contained evaluation task"
            )

    evaluation = _validated_evaluation(
        record.get("evaluation"),
        field=f"{field}.evaluation",
        expected_output=record.get("expected_output"),
        prompt=prompt,
    )
    return TaskDraft(
        task_id=task_id,
        prompt=prompt,
        capability=capability,
        source=HOST_TASK_SOURCES[source_name],
        difficulty=difficulty,
        expected_output=record.get("expected_output"),
        evaluation_hint=evaluation,
        metadata={
            **dict(metadata),
            "provenance": {
                "input": "host_task_manifest",
                "manifest_source": source_name,
                "source_ref": source_ref,
                "ordinal": ordinal,
            },
        },
    )


def _validated_evaluation(
    value: Any,
    *,
    field: str,
    expected_output: Any,
    prompt: str,
    allow_hybrid: bool = True,
) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        raise TaskIngestionError(f"{field} must be an object")
    kind = _required_text(value, "kind", field)
    if kind not in _EVALUATION_FIELDS:
        raise TaskIngestionError(
            f"{field}.kind must be one of {sorted(_EVALUATION_FIELDS)}"
        )
    if kind == "hybrid" and not allow_hybrid:
        raise TaskIngestionError(f"{field} cannot contain nested hybrid")
    _required_text(value, "failure_feedback", field)
    unknown = set(value) - _EVALUATION_FIELDS[kind]
    if unknown:
        raise TaskIngestionError(
            f"{field} has unsupported fields for {kind}: {sorted(unknown)}"
        )
    _optional_object(value.get("criteria", {}), f"{field}.criteria")
    threshold = value.get("pass_threshold")
    if threshold is not None:
        number = _finite_number(threshold, f"{field}.pass_threshold")
        if not 0.0 <= number <= 1.0:
            raise TaskIngestionError(
                f"{field}.pass_threshold must be between 0 and 1"
            )

    if kind == "programmatic":
        checks = value.get("checks")
        if not _is_array(checks) or not checks:
            raise TaskIngestionError(
                f"{field}.checks must be a non-empty array"
            )
        for index, check in enumerate(checks):
            if not isinstance(check, Mapping):
                raise TaskIngestionError(
                    f"{field}.checks[{index}] must be an object"
                )
            try:
                validate_check_config(check)
            except EvaluationConfigError as exc:
                raise TaskIngestionError(f"{field}: {exc}") from exc
            semantic_error = open_ended_exact_text_reason(
                prompt=prompt,
                reference=check.get("value"),
                method=str(check.get("type", "")),
            )
            if semantic_error:
                raise TaskIngestionError(
                    f"{field}.checks[{index}]: {semantic_error}"
                )
    elif kind == "reference":
        if expected_output is None and "reference" not in value:
            raise TaskIngestionError(
                f"{field} requires expected_output or evaluation.reference"
            )
        method = str(value.get("method", "normalized_exact"))
        if method not in REFERENCE_METHODS:
            raise TaskIngestionError(
                f"{field}.method must be one of {sorted(REFERENCE_METHODS)}"
            )
        _optional_object(value.get("config", {}), f"{field}.config")
        reference = value.get("reference", expected_output)
        semantic_error = open_ended_exact_text_reason(
            prompt=prompt,
            reference=reference,
            method=method,
        )
        if semantic_error:
            raise TaskIngestionError(f"{field}: {semantic_error}")
    elif kind == "rubric_judge":
        _validate_rubric(value.get("rubric"), field=f"{field}.rubric")
        _optional_object(value.get("config", {}), f"{field}.config")
    else:
        components = value.get("components")
        if not _is_array(components) or len(components) < 2:
            raise TaskIngestionError(
                f"{field}.components must contain at least two evaluations"
            )
        for index, component in enumerate(components):
            _validated_evaluation(
                component,
                field=f"{field}.components[{index}]",
                expected_output=expected_output,
                prompt=prompt,
                allow_hybrid=False,
            )
        weights = value.get("weights")
        if not _is_array(weights) or len(weights) != len(components):
            raise TaskIngestionError(
                f"{field}.weights must match component count"
            )
        if any(
            _finite_number(weight, f"{field}.weights[{index}]") <= 0
            for index, weight in enumerate(weights)
        ):
            raise TaskIngestionError(f"{field}.weights must be positive")
    return dict(value)


def _evaluation_schema(*, allow_hybrid: bool = True) -> dict[str, Any]:
    common = {
        "criteria": {"type": "object"},
        "pass_threshold": {"type": "number", "minimum": 0, "maximum": 1},
        "failure_feedback": {"type": "string", "minLength": 1},
    }
    variants: list[dict[str, Any]] = [
        {
            "type": "object",
            "properties": {
                "kind": {"const": "programmatic"},
                "checks": {
                    "type": "array",
                    "minItems": 1,
                    "items": {"type": "object"},
                },
                "config": {"type": "object"},
                **common,
            },
            "required": ["kind", "checks", "failure_feedback"],
            "additionalProperties": False,
        },
        {
            "type": "object",
            "properties": {
                "kind": {"const": "reference"},
                "reference": {
                    "description": (
                        "Only for a uniquely correct deterministic answer; "
                        "open-ended natural-language generation must use "
                        "rubric_judge."
                    )
                },
                "method": {"type": "string", "enum": sorted(REFERENCE_METHODS)},
                "config": {"type": "object"},
                **common,
            },
            "required": ["kind", "failure_feedback"],
            "additionalProperties": False,
        },
        {
            "type": "object",
            "properties": {
                "kind": {"const": "rubric_judge"},
                "rubric": {
                    "type": "object",
                    "properties": {
                        "dimensions": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {"type": "string", "minLength": 1},
                                    "description": {
                                        "type": "string",
                                        "minLength": 1,
                                    },
                                    "weight": {
                                        "type": "number",
                                        "exclusiveMinimum": 0,
                                    },
                                },
                                "required": ["name", "description", "weight"],
                                "additionalProperties": False,
                            },
                        },
                        "scale": {
                            "type": "object",
                            "properties": {
                                "minimum": {"type": "number"},
                                "maximum": {"type": "number"},
                            },
                            "required": ["minimum", "maximum"],
                            "additionalProperties": False,
                        },
                    },
                    "required": ["dimensions"],
                    "additionalProperties": False,
                },
                "config": {"type": "object"},
                **common,
            },
            "required": ["kind", "rubric", "failure_feedback"],
            "additionalProperties": False,
        },
    ]
    if allow_hybrid:
        variants.append(
            {
                "type": "object",
                "properties": {
                    "kind": {"const": "hybrid"},
                    "components": {
                        "type": "array",
                        "minItems": 2,
                        "items": _evaluation_schema(allow_hybrid=False),
                    },
                    "weights": {
                        "type": "array",
                        "minItems": 2,
                        "items": {"type": "number", "exclusiveMinimum": 0},
                    },
                    **common,
                },
                "required": [
                    "kind",
                    "components",
                    "weights",
                    "failure_feedback",
                ],
                "additionalProperties": False,
            }
        )
    return {
        "description": "Frozen explicit evaluation; select by kind and include failure feedback.",
        "oneOf": variants,
    }


def _validate_rubric(value: Any, *, field: str) -> None:
    if not isinstance(value, Mapping):
        raise TaskIngestionError(f"{field} must be an object")
    dimensions = value.get("dimensions")
    if not _is_array(dimensions) or not dimensions:
        raise TaskIngestionError(
            f"{field}.dimensions must be a non-empty array"
        )
    names: list[str] = []
    for index, dimension in enumerate(dimensions):
        item_field = f"{field}.dimensions[{index}]"
        if not isinstance(dimension, Mapping):
            raise TaskIngestionError(f"{item_field} must be an object")
        unknown = set(dimension) - {"name", "description", "weight"}
        if unknown:
            raise TaskIngestionError(
                f"{item_field} has unsupported fields: {sorted(unknown)}"
            )
        names.append(_required_text(dimension, "name", item_field))
        _required_text(dimension, "description", item_field)
        weight = _finite_number(dimension.get("weight"), f"{item_field}.weight")
        if weight <= 0:
            raise TaskIngestionError(f"{item_field}.weight must be positive")
    if len(set(names)) != len(names):
        raise TaskIngestionError(f"{field} dimension names must be unique")
    scale = value.get("scale")
    if scale is not None:
        if not isinstance(scale, Mapping):
            raise TaskIngestionError(f"{field}.scale must be an object")
        minimum = _finite_number(scale.get("minimum"), f"{field}.scale.minimum")
        maximum = _finite_number(scale.get("maximum"), f"{field}.scale.maximum")
        if maximum <= minimum:
            raise TaskIngestionError(
                f"{field}.scale.maximum must exceed minimum"
            )


def _required_text(value: Mapping[str, Any], name: str, field: str) -> str:
    item = value.get(name)
    if not isinstance(item, str) or not item.strip():
        raise TaskIngestionError(f"{field}.{name} must be non-empty text")
    return item.strip()


def _optional_object(value: Any, field: str) -> None:
    if not isinstance(value, Mapping):
        raise TaskIngestionError(f"{field} must be an object")


def _finite_number(value: Any, field: str) -> float:
    if isinstance(value, bool):
        raise TaskIngestionError(f"{field} must be a finite number")
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise TaskIngestionError(f"{field} must be a finite number") from exc
    if not math.isfinite(number):
        raise TaskIngestionError(f"{field} must be a finite number")
    return number


def _is_array(value: Any) -> bool:
    return isinstance(value, Sequence) and not isinstance(
        value, (str, bytes, bytearray)
    )


def _normalized_prompt(value: str) -> str:
    return " ".join(value.casefold().split())


def _is_http_url(value: str) -> bool:
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


__all__ = [
    "HOST_TASK_SOURCES",
    "TASK_DIFFICULTIES",
    "TASK_MANIFEST_SCHEMA_VERSION",
    "ingest_task_manifest",
    "task_manifest_schema",
]
